// Generate mock loan data
export const mockLoans = [
  {
    id: "loan1",
    name: "Maria's Maize Farm",
    country: "KE",
    sector: "Crop",
    amount: 200,
    funded: 120,
    apr: 12,
    term: 6,
    insurance: ["drought"],
    story:
      "I need funds to purchase drought-resistant seeds for my 2-acre maize farm. This will help me increase yields even during dry seasons.",
    image: "/placeholder.svg?height=192&width=384",
    createdAt: new Date(2025, 4, 1),
  },
  {
    id: "loan2",
    name: "John's Retail Shop",
    country: "UG",
    sector: "Retail",
    amount: 350,
    funded: 200,
    apr: 10,
    term: 12,
    insurance: ["flood"],
    story:
      "I run a small retail shop selling household goods. This loan will help me expand my inventory and serve more customers in my village.",
    image: "/placeholder.svg?height=192&width=384",
    createdAt: new Date(2025, 4, 5),
  },
  {
    id: "loan3",
    name: "Village Cooperative",
    country: "TZ",
    sector: "Services",
    amount: 500,
    funded: 350,
    apr: 8,
    term: 9,
    insurance: ["drought", "flood"],
    story:
      "Our cooperative provides shared equipment for 15 small-scale farmers. We need to purchase a new water pump for irrigation during dry seasons.",
    image: "/placeholder.svg?height=192&width=384",
    createdAt: new Date(2025, 4, 10),
  },
  {
    id: "loan4",
    name: "Rice Farmers Group",
    country: "BD",
    sector: "Crop",
    amount: 300,
    funded: 150,
    apr: 9,
    term: 6,
    insurance: ["flood", "cyclone"],
    story:
      "We are 5 rice farmers who need funds to repair our irrigation system before the planting season. This will benefit all our families.",
    image: "/placeholder.svg?height=192&width=384",
    createdAt: new Date(2025, 4, 15),
  },
  {
    id: "loan5",
    name: "Coastal Fishery",
    country: "PH",
    sector: "Livestock",
    amount: 400,
    funded: 100,
    apr: 11,
    term: 8,
    insurance: ["cyclone"],
    story:
      "I run a small fishing business and need to repair my boat and nets after the recent storm. This will help me resume operations quickly.",
    image: "/placeholder.svg?height=192&width=384",
    createdAt: new Date(2025, 4, 20),
  },
  {
    id: "loan6",
    name: "Women's Textile Cooperative",
    country: "KH",
    sector: "Services",
    amount: 250,
    funded: 200,
    apr: 10,
    term: 10,
    insurance: [],
    story:
      "Our cooperative of 8 women creates traditional textiles. We need to purchase raw materials in bulk to fulfill a large order from a hotel chain.",
    image: "/placeholder.svg?height=192&width=384",
    createdAt: new Date(2025, 4, 25),
  },
]
